export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_SORT_DEFAULT = 'SET_SORT_DEFAULT';
export const SET_SORT_LOW_TO_HIGH = 'SET_SORT_LOW_TO_HIGH';
export const SET_SORT_HIGH_TO_LOW = 'SET_SORT_HIGH_TO_LOW';
export const SET_SORT_TO_TOMAN = 'SET_SORT_TO_TOMAN';
export const SET_SORT_TO_TETHER = 'SET_SORT_TO_TETHER';
